# Generated by Django 5.1.3 on 2024-11-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subusers',
            name='subscribed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
