# Generated by Django 5.1.3 on 2024-11-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_subusers_subscribed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subusers',
            name='subscribed_at',
        ),
    ]
